name = "smartsearch"
main = "src/worker.js"
compatibility_date = "2025-12-17"
workers_dev = false
route = "smartsearch.fyi/*"

# KV Namespace configuration
[[kv_namespaces]]
binding = "RATE_LIMIT_STORE"
id = "3f4fd9038efa45c9b7e00a6347c3f29d"

# Disable logging by not defining any log settings
# Disable analytics by not defining any datasets

[site]
bucket = "./assets"

# Static asset handling with strict rules
[[rules]]
type = "Text"
globs = ["*.css", "*.html", "opensearch.xml"]
fallthrough = false

[[rules]]
type = "Data"
globs = ["icons/*.{png,ico}", "*.{png,ico,jpg,jpeg}"]
fallthrough = false
