name = "smartsearch"
main = "src/worker.js"
compatibility_date = "2024-04-20"

# Disable logging by not defining any log settings
# Disable analytics by not defining any datasets

[site]
bucket = "./assets" 