name = "smartsearch"
main = "src/worker.js"
compatibility_date = "2025-04-20"

# KV Namespace configuration
[[kv_namespaces]]
binding = "RATE_LIMIT_STORE"
id = "f7d4a7a18e494bcdacf659fea21f53f9"

# Disable logging by not defining any log settings
# Disable analytics by not defining any datasets

[site]
bucket = "./assets"

# Static asset handling with strict rules
[[rules]]
type = "Text"
globs = ["*.css", "*.html", "opensearch.xml"]
fallthrough = false

[[rules]]
type = "Data"
globs = ["icons/*.{png,ico}", "*.{png,ico,jpg,jpeg}"]
fallthrough = false

[env.production]
route = "smartsearch.fyi/*" 