name = "smartsearch"
main = "src/worker.js"
compatibility_date = "2025-04-20"

# Disable logging by not defining any log settings
# Disable analytics by not defining any datasets

# KV Namespace for rate limiting
kv_namespaces = [
  { binding = "RATE_LIMITS", id = "0be9819908b244c780e58f8a4999dd72" }
]

[site]
bucket = "./assets"

[build]
command = ""

# Ensure all assets are served
[build.upload]
format = "service-worker"

# Static asset handling
[[rules]]
type = "Text"
globs = ["**/*.{css,html,xml}"]
fallthrough = false

[[rules]]
type = "Data"
globs = ["**/*.{png,ico,jpg,jpeg,gif}"]
fallthrough = false

[env.production]
route = "smartsearch.lev-jampolsky.workers.dev/*"

# Asset handling
[site.static]
include = ["**/*"]
exclude = [] 